// https://json-generator.com/#

const config_tecla = [
    {
      "_id": "63810c851fb44187e64ead05",
      "index": 0,
      "cols_btn": [
        {
          "_id": "63810c85ef1b2998680789fc",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c858b0c747025e0f25a",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8509cc14526e3b8cec",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85700fa2970272838e",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c851cfdb617d25ede43",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85505e3b1fb4a9300b",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8539136d5bca234738",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85eb15bdde163e2345",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85c927ca0f75bad5c0",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85ab0559ab0a7d70bb",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85ae258fabae49aaeb",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85aa90292b7e7cb540",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8561fe65d46742742c",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 24px;"
        },
        {
          "_id": "63810c859226983fe36d457e",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c854611ff4bbbdd363b",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c859f534e2457767366",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    },
    {
      "_id": "63810c850b4a59ee0fca5da6",
      "index": 1,
      "cols_btn": [
        {
          "_id": "63810c857b76066ae5166092",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85fed5f6c6a0069d6d",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c851d8db1a0424d22e4",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c853b3d65b8150c2551",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c854b6a03324fdab205",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85102d05edb61dccae",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c853b12a3a72accc804",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85d895209e2ebe77e5",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85017b145778024a9d",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85c7ef659259dfa82b",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c856159d4f49770c25c",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8585868ff314713eae",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c855c53ac257e41ef38",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8501573163eed6fff0",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c850c489d61643df5f9",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85e6e2dda8319c6892",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    },
    {
      "_id": "63810c85d29b7c918b0162b3",
      "index": 2,
      "cols_btn": [
        {
          "_id": "63810c85c7566428e1fbf480",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8597231aa61b202161",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8517c9b7941597546f",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85a70f9acd2bf56a88",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85fc7beb8cf2d7ea88",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8593f7687b1d5ebe54",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c858d90bd54c41759d9",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8526c35c8ae545c5ab",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c851831ddc58c5ab0af",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85b15c0a572499e836",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85f5dad2fabe962c57",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c851fa044624a1e2690",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85e555518037c8643f",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c859239897178e753f5",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8503376706cde71453",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85dc50075850e4c086",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    },
    {
      "_id": "63810c85d7b76bd6bf8790bc",
      "index": 3,
      "cols_btn": [
        {
          "_id": "63810c850dfc8de500e21fa6",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c851cc85daf3885e0f3",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8538f4165df89cca42",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85aff2b7b4e7718a39",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85aa99bce27f9fd968",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8550a684ba48f643cc",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85ff2d5173d4e93ea0",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85fe8d8bdfa10af5ee",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8559cff29a663fbae1",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8529b829520dfc3706",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c853fa1745f4dfb908f",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c858d05140c5735ea32",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8577b710b19984cb4c",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8537b6662cd7a66911",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8502799eefbfc65772",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c850e2c4a77f93ca550",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    },
    {
      "_id": "63810c8532b74587223d57c7",
      "index": 4,
      "cols_btn": [
        {
          "_id": "63810c85f4281b2775264995",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8524352b9281c5c836",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85570f9505d6c1c663",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85cabaa00b64f73b80",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85e30e345b3dffbf2c",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85615dd4c323a20450",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85b544dfd0047ec736",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c858791f017b9b6c010",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85aa9116ef53af7a3f",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8529b3f85a19b009ac",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c854c4c357a9c12cee3",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c858f58f6c26803951c",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85f04f68b5b7e18d29",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85fe2e687c9aa2dad6",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8521f7c2170b0e85ab",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c857cc4d9766597d1d2",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    },
    {
      "_id": "63810c85ceb01cb69f75b1a1",
      "index": 5,
      "cols_btn": [
        {
          "_id": "63810c85c9550e7565bd9196",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c853b5d03588d4ae9ec",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c852585076896d7638f",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c853545bdf1f568ef9e",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85f4b5eae1325f3b87",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c858f53c86fe6e9d9ab",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c854320291ffaf3e9c4",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8504bb80edd61c652a",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85afcf19eb16e6593e",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c850f5a919760ba1a95",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85b217e7f8281ed8bd",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85061be9d82a2f7c67",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c850b5b5e97582166b7",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8558236c6be95ac15f",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85c0c2da26ff17bbcc",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85b5c0a0d1861f3404",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    },
    {
      "_id": "63810c85ef8b7449a2911905",
      "index": 6,
      "cols_btn": [
        {
          "_id": "63810c85501d3b4781e26ccf",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85b47e80518f338a8e",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c851170332c961de3c4",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c856658cf9c0e7f44fd",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85317879613d7b691d",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8514803fbec4afac4d",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8560960fc0e0162be0",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c854232e7e8ddc9af22",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c859d31b3e69e9c3884",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85dad96ec362d2abfe",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85897987c1476183db",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8565d751abe004e832",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85e43db282e5e50c59",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85481031498481ae66",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8576b2e87f5594fd4b",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85e68f88bc8323f80b",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    },
    {
      "_id": "63810c85e68995e2f0d34691",
      "index": 7,
      "cols_btn": [
        {
          "_id": "63810c8513ca7b10f70ab336",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85a9d17dd3468886f7",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8570e98e647ada4c23",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c850733daf7191cb452",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c850e8ca25bfb54a9b0",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8591867447d0196515",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c850dd43e35162a72a7",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85766dfdcb6d4e21c3",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85c5c0f6643349edee",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8577b70923921cdc0a",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c859c02838f47ff0511",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c851f6fe6c49c612397",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8567cbfdba13db26e3",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85b0308696ba36211f",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85c2faf3ab4d8806d7",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85b9fd752992820ce6",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    },
    {
      "_id": "63810c85172efb4de11c5889",
      "index": 8,
      "cols_btn": [
        {
          "_id": "63810c85aec7a41754f215ed",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85f83b11f232f7d333",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c852863344c63dd75b1",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8592aaa2d629078ae0",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c858eab543547fea8d8",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c853f1eebfea49091e4",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c855a1131a92ff9832a",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85a82ce0301279aa6b",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85e6d5bab8eb256e58",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c857d480e400cf2255f",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85f856ccfc5335666c",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c853b0e87379eb8b1c6",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c855f2ac1ffa356bb06",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85876fb023a07291d0",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85d0195e2a4c145d92",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85540a120d7a2462b0",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    },
    {
      "_id": "63810c85b234ad8eabc931dc",
      "index": 9,
      "cols_btn": [
        {
          "_id": "63810c85359a43937a6dfdaa",
          "index": 0,
          "number": 1,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85dbe060f4ea9f41e4",
          "index": 1,
          "number": 2,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8584324e43a55cfe86",
          "index": 2,
          "number": 3,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85d1d12db6a5e4b650",
          "index": 3,
          "number": 4,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85c5fa3241eefa9d63",
          "index": 4,
          "number": 5,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85330254acdf18843c",
          "index": 5,
          "number": 6,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85361c810b31f474bc",
          "index": 6,
          "number": 7,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85a48d62d0f8f0e16f",
          "index": 7,
          "number": 8,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85dc791c4e8b0087a1",
          "index": 8,
          "number": 9,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c858ba11175cbf6fe24",
          "index": 9,
          "number": 10,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c856c7cbbd87816ad12",
          "index": 10,
          "number": 11,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85cef996c656a53f44",
          "index": 11,
          "number": 12,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85dd00eb9296f014ea",
          "index": 12,
          "number": 13,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c85d19efb0e554736f8",
          "index": 13,
          "number": 14,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c8511ecf554d713e1ad",
          "index": 14,
          "number": 15,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        },
        {
          "_id": "63810c859d858f9a6034d11d",
          "index": 15,
          "number": 16,
          "key": "A",
          "value": "PAPEL",
          "isVisibleNumber": true,
          "isVisibleKey": true,
          "classNames": "cuadro",
          "fontSizeValue": "14px",
          "fontStyles": "font-size: 14px;"
        }
      ]
    }
  ]