// https://json-generator.com/#

const config_tecla = [
  {
    _id: "6381227c1470ad2f6c293785",
    index: 0,
    cols_btn: [
      {
        _id: "6381227c55bf2c0ae901ca8b",
        index: 0,
        number: 1,
        key: "",
        value: "AVANCE PAPEL",
        isVisibleNumber: false,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 16px; color:  white; font-weight: bolder;",
        btnStyles: "background-color: cornflowerblue;",
      },
      {
        _id: "6381227c5e82a85ed286d195",
        index: 1,
        number: 19,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c56a56e39ee780f10",
        index: 2,
        number: 29,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c8c98df4b61c60217",
        index: 3,
        number: 39,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ce82c347b6c9248f8",
        index: 4,
        number: 49,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ce50345a85e29f2f5",
        index: 5,
        number: 59,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c2d24cb9b8e5da259",
        index: 6,
        number: 69,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c99bd6ee100883a79",
        index: 7,
        number: 79,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c114b16ae110c1a98",
        index: 8,
        number: 89,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cab71878258676777",
        index: 9,
        number: 99,
        key: "",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c666643568fb404cd",
        index: 10,
        number: 109,
        key: "",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c14b1747d910d6e57",
        index: 11,
        number: 119,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c4b9db295db1de172",
        index: 12,
        number: 129,
        key: "",
        value: "SIN RECIBO",
        isVisibleNumber: false,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 16px; font-weight: bolder;",
        btnStyles: "background-color: forestgreen; color:  white;",
      },
      {
        _id: "6381227c8df89c4fe62323cb",
        index: 13,
        number: 139,
        key: "",
        value: "COPIA RECIBO",
        isVisibleNumber: false,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 16px; font-weight: bolder;",
        btnStyles: "background-color: darkgreen; color: white;",
      },
      {
        _id: "6381227c5e8cc83828dd0f17",
        index: 14,
        number: 149,
        key: "",
        value: "ABRIR GAVETA",
        isVisibleNumber: false,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 16px; font-weight: bolder;",
        btnStyles: "background-color: aqua; color: #000;",
      },
      {
        _id: "6381227c352ed6586afcb592",
        index: 15,
        number: 159,
        key: "",
        value: "TERMI- NAR",
        isVisibleNumber: false,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 16px; font-weight: bolder;",
        btnStyles: "",
      },
    ],
  },
  {
    _id: "6381227c30ce2a7c154da9e6",
    index: 1,
    cols_btn: [
      {
        _id: "6381227c28332cafa58827ad",
        index: 0,
        number: 9,
        key: "!",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c3f7f792516ce417a",
        index: 1,
        number: 18,
        key: "@",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c37a00add5f21bd36",
        index: 2,
        number: 28,
        key: "#",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cf6dc2eca344e97fb",
        index: 3,
        number: 38,
        key: "$",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c1e2929944c680914",
        index: 4,
        number: 48,
        key: "%",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cd0a1cbe756291237",
        index: 5,
        number: 58,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cd1bf9b7a7e44eeea",
        index: 6,
        number: 68,
        key: "&",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cc897e7f3b357c727",
        index: 7,
        number: 78,
        key: "*",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cfe9bb31ff32554f0",
        index: 8,
        number: 88,
        key: "(",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c19f5680edecb2b17",
        index: 9,
        number: 98,
        key: ")",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c45a9c8fed3acfd6c",
        index: 10,
        number: 108,
        key: "",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c40d0f355d6de5c5c",
        index: 11,
        number: 118,
        key: "",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ccc7fed7559cd473e",
        index: 12,
        number: 128,
        key: "",
        value: "EMPLE- ADO 1",
        isVisibleNumber: false,
        isVisibleKey: false,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #0a5cab; color:  white;",
      },
      {
        _id: "6381227c685cb1f00ed837e0",
        index: 13,
        number: 138,
        key: "",
        value: "EMPLE- ADO 2",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #0a5cab; color:  white;",
      },
      {
        _id: "6381227ca817855eb719026d",
        index: 14,
        number: 148,
        key: "",
        value: "EMPLE- ADO 3",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #0a5cab; color:  white;",
      },
      {
        _id: "6381227c0bb18651fb0597d3",
        index: 15,
        number: 158,
        key: "",
        value: "EMPLE- ADO 4",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #0a5cab; color:  white;",
      },
    ],
  },
  {
    _id: "6381227c81fc2bea4e5ae802",
    index: 2,
    cols_btn: [
      {
        _id: "6381227ca8a5143bf9c99d13",
        index: 0,
        number: 8,
        key: "Q",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cfec1f043182de8da",
        index: 1,
        number: 17,
        key: "W",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c065ee01a471b9626",
        index: 2,
        number: 27,
        key: "E",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c9d8ff61f00155217",
        index: 3,
        number: 37,
        key: "R",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c7451532686c5e93e",
        index: 4,
        number: 47,
        key: "T",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c5399feada9c9e2cb",
        index: 5,
        number: 57,
        key: "Y",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c597bd579ff7d1ae8",
        index: 6,
        number: 67,
        key: "U",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ce7a57e1f4f644a15",
        index: 7,
        number: 77,
        key: "I",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ca6945972efb8f693",
        index: 8,
        number: 87,
        key: "O",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cafb24619a455d782",
        index: 9,
        number: 97,
        key: "P",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c924aa19422cc77ac",
        index: 10,
        number: 107,
        key: "\\",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c6d4a58f98cecaf64",
        index: 11,
        number: 117,
        key: "",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ce3ca35ece15a84dc",
        index: 12,
        number: 127,
        key: "",
        value: "# CUENTAS",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 12px; font-weight: bolder;",
        btnStyles: "background-color: #a058ad; color:  white;",
      },
      {
        _id: "6381227c02f42a8ff0d7dbeb",
        index: 13,
        number: 137,
        key: "",
        value: "GUARDAR",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "12px",
        valueStyles: "font-size: 12px; font-weight: bolder;",
        btnStyles: "background-color: #a058ad; color:  white;",
      },
      {
        _id: "6381227c1889960bfe44a4fc",
        index: 14,
        number: 147,
        key: "",
        value: "LISTA CUENTAS ABIERTAS",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "12px",
        valueStyles: "font-size: 12px; font-weight: bolder;",
        btnStyles: "background-color: #a058ad; color:  white;",
      },
      {
        _id: "6381227c48c6c1702b06614c",
        index: 15,
        number: 157,
        key: "",
        value: "IMPRIMIR CUENTA",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "12px",
        valueStyles: "font-size: 12px; font-weight: bolder;",
        btnStyles: "background-color: #49c30a; color:  #000;",
      },
    ],
  },
  {
    _id: "6381227cc0dbca922f019237",
    index: 3,
    cols_btn: [
      {
        _id: "6381227c128b2af51e7a37f9",
        index: 0,
        number: 7,
        key: "A",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cbe45dfafe84cadb0",
        index: 1,
        number: 16,
        key: "S",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c8599e29f2cb07142",
        index: 2,
        number: 26,
        key: "D",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227caf88f9354757d4c9",
        index: 3,
        number: 36,
        key: "F",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c44e4bca3c91f95cb",
        index: 4,
        number: 46,
        key: "G",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cbe3d6299ec32a866",
        index: 5,
        number: 56,
        key: "H",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c7b9a881ecacb8baf",
        index: 6,
        number:66,
        key: "J",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c171f82be874eaaed",
        index: 7,
        number: 76,
        key: "K",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c90f3d9b981553cb1",
        index: 8,
        number: 86,
        key: "L",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ca2eac66c0e06ad90",
        index: 9,
        number: 96,
        key: ";",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c63b049ff35de5c10",
        index: 10,
        number: 106,
        key: "",
        value: "",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c16d03452b64bcba7",
        index: 11,
        number: 116,
        key: "",
        value: "",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c0786fc341182e219",
        index: 12,
        number: 126,
        key: "",
        value: "S/. 100.00",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #ed8a07; color:  #000;"
      },
      {
        _id: "6381227cc197c8a8d21ab5ce",
        index: 13,
        number: 136,
        key: "",
        value: "S/. 50.00",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #ed8a07; color:  #000;"
      },
      {
        _id: "6381227c3decb6ec295fbdb8",
        index: 14,
        number: 146,
        key: "",
        value: "S/. 20.00",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #ed8a07; color:  #000;"
      },
      {
        _id: "6381227c799cd98e92f0e18a",
        index: 15,
        number: 16,
        key: "",
        value: "AGREGAR CUENTA",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 13px; font-weight: bolder;",
        btnStyles: "background-color: #f3561a; color:  #000;"
      },
    ],
  },
  {
    _id: "6381227cd9e492465dddc484",
    index: 4,
    cols_btn: [
      {
        _id: "6381227c4c69bf0ce4bfc49e",
        index: 0,
        number: 6,
        key: "Z",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cf33d52a9024c334d",
        index: 1,
        number: 15,
        key: "X",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cb0f82824446f33dd",
        index: 2,
        number: 25,
        key: "C",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ca0b1f82d14437c9b",
        index: 3,
        number: 35,
        key: "V",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c6b2077b42c318e0c",
        index: 4,
        number: 45,
        key: "B",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cf5b13918d1a737f9",
        index: 5,
        number: 55,
        key: "N",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c74bad2f08f0c8b23",
        index: 6,
        number: 65,
        key: "M",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c7350b798282e5297",
        index: 7,
        number: 75,
        key: ",",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c1f800dacdc74f1ab",
        index: 8,
        number: 85,
        key: ".",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c31e047634488cef2",
        index: 9,
        number: 95,
        key: "/",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c82a98cb4fc19fb01",
        index: 10,
        number: 105,
        key: "<",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c37b1d57d8ef66bce",
        index: 11,
        number: 115,
        key: "",
        value: "CAMBIO PRECIO",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #066e6e; color:  #ffb307;"
      },
      {
        _id: "6381227c7278da31ffcf6f1b",
        index: 12,
        number: 125,
        key: "",
        value: "ANULAR",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #fd0000; color:  #ffffff;"
      },
      {
        _id: "6381227c735723d5f953abc3",
        index: 13,
        number: 135,
        key: "",
        value: "CANCELAR TODO",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 12px; font-weight: bolder;",
        btnStyles: "background-color: #fd0000; color:  #ffffff;"
      },
      {
        _id: "6381227cb848f22597ebf394",
        index: 14,
        number: 145,
        key: "",
        value: "MAPA DE MESAS",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 13px; font-weight: bolder;",
        btnStyles: "background-color: #fd0000; color:  #ffffff;"
      },
      {
        _id: "6381227ca39907d8d858930c",
        index: 15,
        number: 16,
        key: "",
        value: "S/. 10.00",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #ed8a07; color:  #000;"
      },
    ],
  },
  {
    _id: "6381227ccad53067e2dfb2a9",
    index: 5,
    cols_btn: [
      {
        _id: "6381227cb071f63f6314bf0f",
        index: 0,
        number: 5,
        key: "MAYUS",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c0e0c358b7fd923a2",
        index: 1,
        number: 14,
        key: "MAYUS",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c50599413f60bf287",
        index: 2,
        number: 24,
        key: "DOBLE",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cd4d8be5c9a85f62c",
        index: 3,
        number: 34,
        key: "ESP",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c5111eccce17137f5",
        index: 4,
        number: 44,
        key: "ESP",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c0e8d508dae7ce556",
        index: 5,
        number: 54,
        key: "ESP",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c0ffdb98551d304e7",
        index: 6,
        number: 64,
        key: "ESP",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c20e7a2e2f7909cf4",
        index: 7,
        number: 74,
        key: "ESP",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c88b04100d41e0621",
        index: 8,
        number: 84,
        key: "ESP",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c7ebb5d1283543c95",
        index: 9,
        number: 94,
        key: "ATR",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c6e1ba8717e8e9f6b",
        index: 10,
        number: 104,
        key: ">",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c5cda2fbe43bc3b16",
        index: 11,
        number: 114,
        key: "",
        value: "DELIVERY",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 13px; font-weight: bolder;",
        btnStyles: "background-color: #ffb307; color:  #000;"
      },
      {
        _id: "6381227cbe280867aaa53aaa",
        index: 12,
        number: 124,
        key: "",
        value: "BORRAR",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #ff68ae; color:  #000;"
      },
      {
        _id: "6381227c7f5a76935b2fa6b9",
        index: 13,
        number: 134,
        key: "",
        value: "PLU",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 24px; font-weight: bolder;",
        btnStyles: "background-color: #fff; color:  #fd0000;"
      },
      {
        _id: "6381227c918a09aab4b4b996",
        index: 14,
        number: 15,
        key: "",
        value: "X HORA",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 20px; font-weight: bolder;",
        btnStyles: "background-color: #0054d3; color:  #ffb307;"
      },
      {
        _id: "6381227ce2b3422f50e748e1",
        index: 15,
        number: 16,
        key: "",
        value: "S/. 5.00",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #ed8a07; color:  #000;"
      },
    ],
  },
  {
    _id: "6381227c75d9a73f1a807751",
    index: 6,
    cols_btn: [
      {
        _id: "6381227c5034381194ed5c71",
        index: 0,
        number: 4,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c5708b94c7e991169",
        index: 1,
        number: 13,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c557d58bc61c4ffb6",
        index: 2,
        number: 23,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c9d25ac62979ee5fb",
        index: 3,
        number: 33,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cc1fc2c05f2ed0b7a",
        index: 4,
        number: 43,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cbe14373af5d4fafa",
        index: 5,
        number: 53,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c53503d4ce0d0d6d1",
        index: 6,
        number: 63,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cb1ca9ff153349be5",
        index: 7,
        number: 73,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c1e13f7683a83c9ce",
        index: 8,
        number: 83,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cff30df961221938a",
        index: 9,
        number: 93,
        key: "",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cf387d881d3c68e19",
        index: 10,
        number: 103,
        key: "",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c9e34d87cd08606ce",
        index: 11,
        number: 113,
        key: "",
        value: "CLIENTE",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #f56149; color:  #000;"
      },
      {
        _id: "6381227cc9a688a8a7d1c146",
        index: 12,
        number: 123,
        key: "",
        value: "7",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c09de0a4b9e824dbc",
        index: 13,
        number: 133,
        key: "",
        value: "8",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c2e5e7f390adff7fb",
        index: 14,
        number: 143,
        key: "",
        value: "9",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227cf39379399da3145e",
        index: 15,
        number: 16,
        key: "",
        value: "FORMA PAGO 3",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #ed8a07; color:  #000;"
      },
    ],
  },
  {
    _id: "6381227c61601fc19dcfe0d2",
    index: 7,
    cols_btn: [
      {
        _id: "6381227c6ea0b9b3635f59fc",
        index: 0,
        number: 3,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c2ae2a5e9becfbbba",
        index: 1,
        number: 12,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c117a1bc6adcaa050",
        index: 2,
        number: 22,
        key: "",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c99578c5320efc3c8",
        index: 3,
        number: 32,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cad5c39d69facbb9e",
        index: 4,
        number: 42,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c4dcd170ca44ad2c6",
        index: 5,
        number: 52,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c3b28dedb431b35dd",
        index: 6,
        number: 62,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c221915d7410f07f9",
        index: 7,
        number: 72,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c8d2df62c4e4c4fae",
        index: 8,
        number: 82,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c90d2e9b801f2c861",
        index: 9,
        number: 92,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c4d12211cb21e36f3",
        index: 10,
        number: 102,
        key: "",
        value: "",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c0cb83a5d561bfc9d",
        index: 11,
        number: 112,
        key: "",
        value: "RUC",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #780000; color:  #fff;"
      },
      {
        _id: "6381227c72c45d7df062de9b",
        index: 12,
        number: 122,
        key: "",
        value: "4",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c82a0d648bfa109c1",
        index: 13,
        number: 132,
        key: "",
        value: "5",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c8e345609c6d78e1b",
        index: 14,
        number: 142,
        key: "",
        value: "6",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c3f57bee14ab95280",
        index: 15,
        number: 16,
        key: "",
        value: "VISA",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 18px; font-weight: bolder;",
        btnStyles: "background-color: #0054d3; color:  #fff;"
      },
    ],
  },
  {
    _id: "6381227c8636222e74af300e",
    index: 8,
    cols_btn: [
      {
        _id: "6381227cd54c5b008a719600",
        index: 0,
        number: 2,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c222146a090d1787f",
        index: 1,
        number: 11,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ce023a3bc1d820915",
        index: 2,
        number: 21,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c0f6cd5a8add7d0b6",
        index: 3,
        number: 31,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c8af3fd034794317a",
        index: 4,
        number: 41,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c62a32de17da7ee56",
        index: 5,
        number: 51,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c10f81b40f8efe1d9",
        index: 6,
        number: 61,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c75083143c4f0170c",
        index: 7,
        number: 71,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ceccab49cf4e02492",
        index: 8,
        number: 81,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ce411ffa9d70e76e4",
        index: 9,
        number: 91,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cd2cf2b546ad3f0d2",
        index: 10,
        number: 101,
        key: "",
        value: "",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c57319a0e3bf299a9",
        index: 11,
        number: 111,
        key: "",
        value: "DESCU- ENTO",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #b34377; color:  #000;"
      },
      {
        _id: "6381227c46769f7a2ca236a8",
        index: 12,
        number: 121,
        key: "",
        value: "1",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c9e62fec307937588",
        index: 13,
        number: 131,
        key: "",
        value: "2",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c2cf6de24b04c491c",
        index: 14,
        number: 141,
        key: "",
        value: "3",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c0fe198d8cbb1f0c6",
        index: 15,
        number: 16,
        key: "",
        value: "SUB TOTAL",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #0a5cab; color:  #000;"
      },
    ],
  },
  {
    _id: "6381227c32b3ff2e91cc8e5c",
    index: 9,
    cols_btn: [
      {
        _id: "6381227c4854cfb4b1ed6d56",
        index: 0,
        number: 1,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cb0114e5b9f6d89d6",
        index: 1,
        number: 10,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c8846c33a5bc3095b",
        index: 2,
        number: 20,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cef3e3a529693a4db",
        index: 3,
        number: 30,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ce0cd98fca39ad624",
        index: 4,
        number: 40,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c62064f97369d791c",
        index: 5,
        number: 50,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227cd7bd6d641d782ffa",
        index: 6,
        number: 60,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c5e866f8db13e8240",
        index: 7,
        number: 70,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c5dbfd4a9101b6c88",
        index: 8,
        number: 80,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c45262e693217a9cc",
        index: 9,
        number: 90,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227ca104f8503f7c89e4",
        index: 10,
        number: 100,
        key: "",
        value: "---",
        isVisibleNumber: true,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px;",
        btnStyles: "",
      },
      {
        _id: "6381227c6b4611a3fd90f7bd",
        index: 11,
        number: 110,
        key: "",
        value: "ADICIO- NAL",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 14px; font-weight: bolder;",
        btnStyles: "background-color: #0a5cab; color:  #000;"
      },
      {
        _id: "6381227cdbdebec722f6a46b",
        index: 12,
        number: 120,
        key: "",
        value: "0",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227cfba8a02c3c369916",
        index: 13,
        number: 130,
        key: "",
        value: "00",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c07e94e109f828824",
        index: 14,
        number: 140,
        key: "",
        value: ".",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 50px; font-weight: bolder;",
        btnStyles: "background-color: #000; color:  #fff;"
      },
      {
        _id: "6381227c08dd15ed1cd1cf95",
        index: 15,
        number: 150,
        key: "",
        value: "EFECTIVO S/.",
        isVisibleNumber: false,
        isVisibleKey: true,
        classNames: "cuadro",
        fontSizeValue: "14px",
        valueStyles: "font-size: 12px; font-weight: bolder;",
        btnStyles: "background-color: #49c30a; color:  #000;"
      },
    ],
  },
];
